server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
     active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Sahil1694/configserver.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true